#!/usr/bin/env python3
"""Validate catalog metadata and its Markdown projection. No network or dependencies."""
from __future__ import annotations

import argparse
from datetime import date, datetime, timezone
import json
from pathlib import Path
import re
import sys
from urllib.parse import urlsplit, urlunsplit

ROOT = Path(__file__).resolve().parents[1]
FIELDS = {"id", "title", "category", "url", "why", "apply", "caveat", "coverage", "reviewed_on", "evidence"}
CATEGORIES = {"guide", "checklist", "program", "tool", "example"}


def validate(data: object, today: date) -> tuple[list[str], list[str]]:
    """Return structural errors and freshness warnings without mutating input."""
    errors: list[str] = []
    warnings: list[str] = []
    if not isinstance(data, dict) or set(data) != {"schema_version", "resources"}:
        return ["root: expected schema_version and resources"], []
    if type(data["schema_version"]) is not int or data["schema_version"] != 1:
        errors.append("schema_version: expected integer 1")
    resources = data["resources"]
    if not isinstance(resources, list) or not resources:
        return errors + ["resources: expected a nonempty list"], warnings
    ids: set[str] = set()
    urls: set[str] = set()
    for index, item in enumerate(resources):
        label = f"resources[{index}]"
        if not isinstance(item, dict) or set(item) != FIELDS:
            errors.append(f"{label}: expected fields {', '.join(sorted(FIELDS))}")
            continue
        invalid = [k for k in FIELDS if not isinstance(item[k], str) or not item[k].strip()]
        if invalid:
            errors.append(f"{label}: nonempty strings required for {', '.join(sorted(invalid))}")
            continue
        ident = item["id"]
        label = f"{label} ({ident})"
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", ident):
            errors.append(f"{label}: id must be lowercase words separated by hyphens")
        if ident in ids:
            errors.append(f"{label}: duplicate id")
        ids.add(ident)
        if item["category"] not in CATEGORIES:
            errors.append(f"{label}: unsupported category")
        if item["evidence"] != "source-reviewed":
            errors.append(f"{label}: evidence must be source-reviewed; runtime trials need separate evidence")
        url = item["url"]
        try:
            parts = urlsplit(url)
            if (parts.scheme != "https" or not parts.hostname or parts.username is not None
                    or parts.password is not None or any(c.isspace() for c in url)
                    or any(c in url for c in '<>"\\')):
                raise ValueError("expected HTTPS URL without credentials, whitespace or unsafe delimiters")
            # Accessing port validates malformed numeric ports; fragments do not create new sources.
            port = parts.port
            host = parts.hostname.lower()
            authority = f"[{host}]" if ':' in host else host
            if port is not None and port != 443:
                authority += f":{port}"
            normalized = urlunsplit(("https", authority, parts.path.rstrip('/'), parts.query, ""))
            if normalized in urls:
                errors.append(f"{label}: duplicate source URL")
            urls.add(normalized)
        except ValueError as exc:
            errors.append(f"{label}: invalid url: {exc}")
        try:
            value = item["reviewed_on"]
            if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
                raise ValueError
            observed = date.fromisoformat(value)
            if observed > today:
                errors.append(f"{label}: reviewed_on is in the future")
            else:
                threshold = 30 if item["category"] == "program" else 180
                if (today - observed).days > threshold:
                    warnings.append(f"{label}: recheck source; last reviewed {observed.isoformat()}")
        except ValueError:
            errors.append(f"{label}: reviewed_on must be a real YYYY-MM-DD date")
    return errors, warnings


def escape(text: str) -> str:
    """Render text fields literally, not as active HTML or Markdown structure."""
    text = " ".join(text.split())
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return re.sub(r"([\\`*_{}\[\]#!|])", r"\\\1", text)


def render(data: dict) -> str:
    """Deterministic view; call only after successful validation."""
    lines = ["# Curated resources", "", "<!-- Generated by tools/catalog.py; edit resources.json. -->", "",
             "Primary sources with a specific use and explicit limits. Source review does not mean",
             "a tool was installed, a workflow was tested or a program accepted this project.", ""]
    for item in sorted(data["resources"], key=lambda r: (r["category"], r["id"])):
        lines += [f"## {escape(item['title'])}", "", f"<{item['url']}>", "",
                  f"**{item['category']} · reviewed {item['reviewed_on']} · {item['evidence']}**", "",
                  f"**Why:** {escape(item['why'])}", "",
                  f"**Apply:** {escape(item['apply'])}", "",
                  f"**Caveat:** {escape(item['caveat'])}", "",
                  f"**Coverage:** {escape(item['coverage'])}", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=ROOT / "catalog/resources.json")
    parser.add_argument("--output", type=Path, default=ROOT / "catalog/README.md")
    parser.add_argument("--write", action="store_true", help="explicitly regenerate the Markdown view")
    args = parser.parse_args(argv)
    try:
        data = json.loads(args.data.read_text(encoding="utf-8"))
        errors, warnings = validate(data, datetime.now(timezone.utc).date())
        for warning in warnings:
            print(f"WARN: {warning}", file=sys.stderr)
        if errors:
            for error in errors:
                print(f"ERROR: {error}", file=sys.stderr)
            return 1
        expected = render(data)
        if args.write:
            args.output.write_text(expected, encoding="utf-8")
        elif not args.output.is_file() or args.output.read_text(encoding="utf-8") != expected:
            print("ERROR: generated catalog is missing or stale; run tools/catalog.py --write", file=sys.stderr)
            return 1
        print(f"OK: {len(data['resources'])} resources; generated catalog is current")
        return 0
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        print(f"ERROR: cannot process catalog: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
